"""Add composite index for inventory

Revision ID: 64b177a80c20
Revises: 
Create Date: 2026-07-13 01:18:43.877951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b177a80c20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_inventory', 'blood_pouches', ['hospital_id', 'groupe_sanguin', 'statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inventory', table_name='blood_pouches')
    # ### end Alembic commands ###
