"""Schema initial

Revision ID: 7540754927c6
Revises: 
Create Date: 2026-07-14 21:28:39.880142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7540754927c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('localisation', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_pouches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('groupe_sanguin', sa.String(length=3), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_prelevement', sa.Date(), nullable=False),
    sa.Column('date_peremption', sa.Date(), nullable=False),
    sa.Column('qr_code_b64', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory', 'blood_pouches', ['hospital_id', 'groupe_sanguin', 'statut'], unique=False)
    op.create_index(op.f('ix_blood_pouches_date_peremption'), 'blood_pouches', ['date_peremption'], unique=False)
    op.create_index(op.f('ix_blood_pouches_groupe_sanguin'), 'blood_pouches', ['groupe_sanguin'], unique=False)
    op.create_index(op.f('ix_blood_pouches_hospital_id'), 'blood_pouches', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_blood_pouches_statut'), 'blood_pouches', ['statut'], unique=False)
    op.create_index(op.f('ix_blood_pouches_uid'), 'blood_pouches', ['uid'], unique=True)
    op.create_table('collection_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('localisation', sa.String(length=200), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('horaires', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_points_localisation'), 'collection_points', ['localisation'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupe_sanguin', sa.String(length=3), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=False),
    sa.Column('portee', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('groupe_sanguin', sa.String(length=3), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('urgence', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_requests_hospital_id'), 'blood_requests', ['hospital_id'], unique=False)
    op.create_table('donor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('groupe_sanguin', sa.String(length=3), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('localisation', sa.String(length=200), nullable=False),
    sa.Column('date_dernier_don', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_profiles_groupe_sanguin'), 'donor_profiles', ['groupe_sanguin'], unique=False)
    op.create_index(op.f('ix_donor_profiles_localisation'), 'donor_profiles', ['localisation'], unique=False)
    op.create_index(op.f('ix_donor_profiles_user_id'), 'donor_profiles', ['user_id'], unique=True)
    op.create_table('transfer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_hospital_id', sa.Integer(), nullable=False),
    sa.Column('target_hospital_id', sa.Integer(), nullable=False),
    sa.Column('groupe_sanguin', sa.String(length=3), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['target_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_responses_alert_id'), 'alert_responses', ['alert_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('collection_point_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_donor_id'), 'appointments', ['donor_id'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('collection_point_id', sa.Integer(), nullable=False),
    sa.Column('groupe_sanguin', sa.String(length=3), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_appointments_donor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_alert_responses_alert_id'), table_name='alert_responses')
    op.drop_table('alert_responses')
    op.drop_table('transfer_orders')
    op.drop_index(op.f('ix_donor_profiles_user_id'), table_name='donor_profiles')
    op.drop_index(op.f('ix_donor_profiles_localisation'), table_name='donor_profiles')
    op.drop_index(op.f('ix_donor_profiles_groupe_sanguin'), table_name='donor_profiles')
    op.drop_table('donor_profiles')
    op.drop_index(op.f('ix_blood_requests_hospital_id'), table_name='blood_requests')
    op.drop_table('blood_requests')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_collection_points_localisation'), table_name='collection_points')
    op.drop_table('collection_points')
    op.drop_index(op.f('ix_blood_pouches_uid'), table_name='blood_pouches')
    op.drop_index(op.f('ix_blood_pouches_statut'), table_name='blood_pouches')
    op.drop_index(op.f('ix_blood_pouches_hospital_id'), table_name='blood_pouches')
    op.drop_index(op.f('ix_blood_pouches_groupe_sanguin'), table_name='blood_pouches')
    op.drop_index(op.f('ix_blood_pouches_date_peremption'), table_name='blood_pouches')
    op.drop_index('idx_inventory', table_name='blood_pouches')
    op.drop_table('blood_pouches')
    op.drop_table('hospitals')
    op.drop_table('configurations')
    # ### end Alembic commands ###
